//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace delete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeData
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_last_name { get; set; }
        public int emp_age { get; set; }
    }
}
