//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace createUpdate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentData
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Fees { get; set; }
    }
}
