//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productperchase
    {
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public int Product_Quality { get; set; }
        public int product_price { get; set; }
    }
}
