//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sale_puchase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale1
    {
        public int id { get; set; }
        public string sale_pd_name { get; set; }
        public int sale_pd_quantity { get; set; }
        public int sale_pd_price { get; set; }
        public System.DateTime sale_pd_date { get; set; }
    }
}
