//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities1 : DbContext
    {
        public projectEntities1()
            : base("name=projectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<saleProduct> saleProducts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }

        public System.Data.Entity.DbSet<MVC_Inventory_Project.Models.multiclass> multiclasses { get; set; }
    }
}
