//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Produc_id { get; set; }
        public string Product_Name { get; set; }
        public int Produc_Quantity { get; set; }
        public int Produc_Price { get; set; }
        public Nullable<System.DateTime> Produc_Date { get; set; }
    }
}
